# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/olivier/mao/borderlands/Borderlands

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/olivier/mao/borderlands/Borderlands

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olivier/mao/borderlands/Borderlands/CMakeFiles /home/olivier/mao/borderlands/Borderlands/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olivier/mao/borderlands/Borderlands/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Frontieres_translations

# Build rule for target.
Frontieres_translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frontieres_translations
.PHONY : Frontieres_translations

# fast build rule for target.
Frontieres_translations/fast:
	$(MAKE) -f CMakeFiles/Frontieres_translations.dir/build.make CMakeFiles/Frontieres_translations.dir/build
.PHONY : Frontieres_translations/fast

#=============================================================================
# Target rules for targets named Frontieres

# Build rule for target.
Frontieres: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frontieres
.PHONY : Frontieres

# fast build rule for target.
Frontieres/fast:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/build
.PHONY : Frontieres/fast

AudioFileSet.o: AudioFileSet.cpp.o

.PHONY : AudioFileSet.o

# target to build an object file
AudioFileSet.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/AudioFileSet.cpp.o
.PHONY : AudioFileSet.cpp.o

AudioFileSet.i: AudioFileSet.cpp.i

.PHONY : AudioFileSet.i

# target to preprocess a source file
AudioFileSet.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/AudioFileSet.cpp.i
.PHONY : AudioFileSet.cpp.i

AudioFileSet.s: AudioFileSet.cpp.s

.PHONY : AudioFileSet.s

# target to generate assembly for a file
AudioFileSet.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/AudioFileSet.cpp.s
.PHONY : AudioFileSet.cpp.s

Frontieres.o: Frontieres.cpp.o

.PHONY : Frontieres.o

# target to build an object file
Frontieres.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Frontieres.cpp.o
.PHONY : Frontieres.cpp.o

Frontieres.i: Frontieres.cpp.i

.PHONY : Frontieres.i

# target to preprocess a source file
Frontieres.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Frontieres.cpp.i
.PHONY : Frontieres.cpp.i

Frontieres.s: Frontieres.cpp.s

.PHONY : Frontieres.s

# target to generate assembly for a file
Frontieres.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Frontieres.cpp.s
.PHONY : Frontieres.cpp.s

GTime.o: GTime.cpp.o

.PHONY : GTime.o

# target to build an object file
GTime.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GTime.cpp.o
.PHONY : GTime.cpp.o

GTime.i: GTime.cpp.i

.PHONY : GTime.i

# target to preprocess a source file
GTime.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GTime.cpp.i
.PHONY : GTime.cpp.i

GTime.s: GTime.cpp.s

.PHONY : GTime.s

# target to generate assembly for a file
GTime.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GTime.cpp.s
.PHONY : GTime.cpp.s

GrainCluster.o: GrainCluster.cpp.o

.PHONY : GrainCluster.o

# target to build an object file
GrainCluster.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainCluster.cpp.o
.PHONY : GrainCluster.cpp.o

GrainCluster.i: GrainCluster.cpp.i

.PHONY : GrainCluster.i

# target to preprocess a source file
GrainCluster.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainCluster.cpp.i
.PHONY : GrainCluster.cpp.i

GrainCluster.s: GrainCluster.cpp.s

.PHONY : GrainCluster.s

# target to generate assembly for a file
GrainCluster.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainCluster.cpp.s
.PHONY : GrainCluster.cpp.s

GrainVoice.o: GrainVoice.cpp.o

.PHONY : GrainVoice.o

# target to build an object file
GrainVoice.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainVoice.cpp.o
.PHONY : GrainVoice.cpp.o

GrainVoice.i: GrainVoice.cpp.i

.PHONY : GrainVoice.i

# target to preprocess a source file
GrainVoice.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainVoice.cpp.i
.PHONY : GrainVoice.cpp.i

GrainVoice.s: GrainVoice.cpp.s

.PHONY : GrainVoice.s

# target to generate assembly for a file
GrainVoice.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/GrainVoice.cpp.s
.PHONY : GrainVoice.cpp.s

MyGLApplication.o: MyGLApplication.cpp.o

.PHONY : MyGLApplication.o

# target to build an object file
MyGLApplication.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLApplication.cpp.o
.PHONY : MyGLApplication.cpp.o

MyGLApplication.i: MyGLApplication.cpp.i

.PHONY : MyGLApplication.i

# target to preprocess a source file
MyGLApplication.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLApplication.cpp.i
.PHONY : MyGLApplication.cpp.i

MyGLApplication.s: MyGLApplication.cpp.s

.PHONY : MyGLApplication.s

# target to generate assembly for a file
MyGLApplication.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLApplication.cpp.s
.PHONY : MyGLApplication.cpp.s

MyGLWindow.o: MyGLWindow.cpp.o

.PHONY : MyGLWindow.o

# target to build an object file
MyGLWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLWindow.cpp.o
.PHONY : MyGLWindow.cpp.o

MyGLWindow.i: MyGLWindow.cpp.i

.PHONY : MyGLWindow.i

# target to preprocess a source file
MyGLWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLWindow.cpp.i
.PHONY : MyGLWindow.cpp.i

MyGLWindow.s: MyGLWindow.cpp.s

.PHONY : MyGLWindow.s

# target to generate assembly for a file
MyGLWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyGLWindow.cpp.s
.PHONY : MyGLWindow.cpp.s

MyRtAudio.o: MyRtAudio.cpp.o

.PHONY : MyRtAudio.o

# target to build an object file
MyRtAudio.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyRtAudio.cpp.o
.PHONY : MyRtAudio.cpp.o

MyRtAudio.i: MyRtAudio.cpp.i

.PHONY : MyRtAudio.i

# target to preprocess a source file
MyRtAudio.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyRtAudio.cpp.i
.PHONY : MyRtAudio.cpp.i

MyRtAudio.s: MyRtAudio.cpp.s

.PHONY : MyRtAudio.s

# target to generate assembly for a file
MyRtAudio.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/MyRtAudio.cpp.s
.PHONY : MyRtAudio.cpp.s

SoundRect.o: SoundRect.cpp.o

.PHONY : SoundRect.o

# target to build an object file
SoundRect.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/SoundRect.cpp.o
.PHONY : SoundRect.cpp.o

SoundRect.i: SoundRect.cpp.i

.PHONY : SoundRect.i

# target to preprocess a source file
SoundRect.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/SoundRect.cpp.i
.PHONY : SoundRect.cpp.i

SoundRect.s: SoundRect.cpp.s

.PHONY : SoundRect.s

# target to generate assembly for a file
SoundRect.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/SoundRect.cpp.s
.PHONY : SoundRect.cpp.s

Thread.o: Thread.cpp.o

.PHONY : Thread.o

# target to build an object file
Thread.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Thread.cpp.o
.PHONY : Thread.cpp.o

Thread.i: Thread.cpp.i

.PHONY : Thread.i

# target to preprocess a source file
Thread.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Thread.cpp.i
.PHONY : Thread.cpp.i

Thread.s: Thread.cpp.s

.PHONY : Thread.s

# target to generate assembly for a file
Thread.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Thread.cpp.s
.PHONY : Thread.cpp.s

Window.o: Window.cpp.o

.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/Window.cpp.s
.PHONY : Window.cpp.s

libraries/QtFont3D/QtFont3D.o: libraries/QtFont3D/QtFont3D.cpp.o

.PHONY : libraries/QtFont3D/QtFont3D.o

# target to build an object file
libraries/QtFont3D/QtFont3D.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.o
.PHONY : libraries/QtFont3D/QtFont3D.cpp.o

libraries/QtFont3D/QtFont3D.i: libraries/QtFont3D/QtFont3D.cpp.i

.PHONY : libraries/QtFont3D/QtFont3D.i

# target to preprocess a source file
libraries/QtFont3D/QtFont3D.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.i
.PHONY : libraries/QtFont3D/QtFont3D.cpp.i

libraries/QtFont3D/QtFont3D.s: libraries/QtFont3D/QtFont3D.cpp.s

.PHONY : libraries/QtFont3D/QtFont3D.s

# target to generate assembly for a file
libraries/QtFont3D/QtFont3D.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.s
.PHONY : libraries/QtFont3D/QtFont3D.cpp.s

libraries/RtAudio.o: libraries/RtAudio.cpp.o

.PHONY : libraries/RtAudio.o

# target to build an object file
libraries/RtAudio.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.o
.PHONY : libraries/RtAudio.cpp.o

libraries/RtAudio.i: libraries/RtAudio.cpp.i

.PHONY : libraries/RtAudio.i

# target to preprocess a source file
libraries/RtAudio.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.i
.PHONY : libraries/RtAudio.cpp.i

libraries/RtAudio.s: libraries/RtAudio.cpp.s

.PHONY : libraries/RtAudio.s

# target to generate assembly for a file
libraries/RtAudio.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.s
.PHONY : libraries/RtAudio.cpp.s

libraries/RtMidi.o: libraries/RtMidi.cpp.o

.PHONY : libraries/RtMidi.o

# target to build an object file
libraries/RtMidi.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.o
.PHONY : libraries/RtMidi.cpp.o

libraries/RtMidi.i: libraries/RtMidi.cpp.i

.PHONY : libraries/RtMidi.i

# target to preprocess a source file
libraries/RtMidi.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.i
.PHONY : libraries/RtMidi.cpp.i

libraries/RtMidi.s: libraries/RtMidi.cpp.s

.PHONY : libraries/RtMidi.s

# target to generate assembly for a file
libraries/RtMidi.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.s
.PHONY : libraries/RtMidi.cpp.s

libraries/Stk.o: libraries/Stk.cpp.o

.PHONY : libraries/Stk.o

# target to build an object file
libraries/Stk.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.o
.PHONY : libraries/Stk.cpp.o

libraries/Stk.i: libraries/Stk.cpp.i

.PHONY : libraries/Stk.i

# target to preprocess a source file
libraries/Stk.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.i
.PHONY : libraries/Stk.cpp.i

libraries/Stk.s: libraries/Stk.cpp.s

.PHONY : libraries/Stk.s

# target to generate assembly for a file
libraries/Stk.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.s
.PHONY : libraries/Stk.cpp.s

libraries/ring_buffer.o: libraries/ring_buffer.cpp.o

.PHONY : libraries/ring_buffer.o

# target to build an object file
libraries/ring_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.o
.PHONY : libraries/ring_buffer.cpp.o

libraries/ring_buffer.i: libraries/ring_buffer.cpp.i

.PHONY : libraries/ring_buffer.i

# target to preprocess a source file
libraries/ring_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.i
.PHONY : libraries/ring_buffer.cpp.i

libraries/ring_buffer.s: libraries/ring_buffer.cpp.s

.PHONY : libraries/ring_buffer.s

# target to generate assembly for a file
libraries/ring_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.s
.PHONY : libraries/ring_buffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Frontieres_translations"
	@echo "... edit_cache"
	@echo "... Frontieres"
	@echo "... rebuild_cache"
	@echo "... AudioFileSet.o"
	@echo "... AudioFileSet.i"
	@echo "... AudioFileSet.s"
	@echo "... Frontieres.o"
	@echo "... Frontieres.i"
	@echo "... Frontieres.s"
	@echo "... GTime.o"
	@echo "... GTime.i"
	@echo "... GTime.s"
	@echo "... GrainCluster.o"
	@echo "... GrainCluster.i"
	@echo "... GrainCluster.s"
	@echo "... GrainVoice.o"
	@echo "... GrainVoice.i"
	@echo "... GrainVoice.s"
	@echo "... MyGLApplication.o"
	@echo "... MyGLApplication.i"
	@echo "... MyGLApplication.s"
	@echo "... MyGLWindow.o"
	@echo "... MyGLWindow.i"
	@echo "... MyGLWindow.s"
	@echo "... MyRtAudio.o"
	@echo "... MyRtAudio.i"
	@echo "... MyRtAudio.s"
	@echo "... SoundRect.o"
	@echo "... SoundRect.i"
	@echo "... SoundRect.s"
	@echo "... Thread.o"
	@echo "... Thread.i"
	@echo "... Thread.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... libraries/QtFont3D/QtFont3D.o"
	@echo "... libraries/QtFont3D/QtFont3D.i"
	@echo "... libraries/QtFont3D/QtFont3D.s"
	@echo "... libraries/RtAudio.o"
	@echo "... libraries/RtAudio.i"
	@echo "... libraries/RtAudio.s"
	@echo "... libraries/RtMidi.o"
	@echo "... libraries/RtMidi.i"
	@echo "... libraries/RtMidi.s"
	@echo "... libraries/Stk.o"
	@echo "... libraries/Stk.i"
	@echo "... libraries/Stk.s"
	@echo "... libraries/ring_buffer.o"
	@echo "... libraries/ring_buffer.i"
	@echo "... libraries/ring_buffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

