# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/olivier/developpement/Frontieres

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/olivier/developpement/Frontieres

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olivier/developpement/Frontieres/CMakeFiles /home/olivier/developpement/Frontieres/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olivier/developpement/Frontieres/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Frontieres_translations

# Build rule for target.
Frontieres_translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frontieres_translations
.PHONY : Frontieres_translations

# fast build rule for target.
Frontieres_translations/fast:
	$(MAKE) -f CMakeFiles/Frontieres_translations.dir/build.make CMakeFiles/Frontieres_translations.dir/build
.PHONY : Frontieres_translations/fast

#=============================================================================
# Target rules for targets named Frontieres

# Build rule for target.
Frontieres: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frontieres
.PHONY : Frontieres

# fast build rule for target.
Frontieres/fast:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/build
.PHONY : Frontieres/fast

libraries/QtFont3D/QtFont3D.o: libraries/QtFont3D/QtFont3D.cpp.o

.PHONY : libraries/QtFont3D/QtFont3D.o

# target to build an object file
libraries/QtFont3D/QtFont3D.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.o
.PHONY : libraries/QtFont3D/QtFont3D.cpp.o

libraries/QtFont3D/QtFont3D.i: libraries/QtFont3D/QtFont3D.cpp.i

.PHONY : libraries/QtFont3D/QtFont3D.i

# target to preprocess a source file
libraries/QtFont3D/QtFont3D.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.i
.PHONY : libraries/QtFont3D/QtFont3D.cpp.i

libraries/QtFont3D/QtFont3D.s: libraries/QtFont3D/QtFont3D.cpp.s

.PHONY : libraries/QtFont3D/QtFont3D.s

# target to generate assembly for a file
libraries/QtFont3D/QtFont3D.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/QtFont3D/QtFont3D.cpp.s
.PHONY : libraries/QtFont3D/QtFont3D.cpp.s

libraries/RtAudio.o: libraries/RtAudio.cpp.o

.PHONY : libraries/RtAudio.o

# target to build an object file
libraries/RtAudio.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.o
.PHONY : libraries/RtAudio.cpp.o

libraries/RtAudio.i: libraries/RtAudio.cpp.i

.PHONY : libraries/RtAudio.i

# target to preprocess a source file
libraries/RtAudio.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.i
.PHONY : libraries/RtAudio.cpp.i

libraries/RtAudio.s: libraries/RtAudio.cpp.s

.PHONY : libraries/RtAudio.s

# target to generate assembly for a file
libraries/RtAudio.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtAudio.cpp.s
.PHONY : libraries/RtAudio.cpp.s

libraries/RtMidi.o: libraries/RtMidi.cpp.o

.PHONY : libraries/RtMidi.o

# target to build an object file
libraries/RtMidi.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.o
.PHONY : libraries/RtMidi.cpp.o

libraries/RtMidi.i: libraries/RtMidi.cpp.i

.PHONY : libraries/RtMidi.i

# target to preprocess a source file
libraries/RtMidi.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.i
.PHONY : libraries/RtMidi.cpp.i

libraries/RtMidi.s: libraries/RtMidi.cpp.s

.PHONY : libraries/RtMidi.s

# target to generate assembly for a file
libraries/RtMidi.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/RtMidi.cpp.s
.PHONY : libraries/RtMidi.cpp.s

libraries/Stk.o: libraries/Stk.cpp.o

.PHONY : libraries/Stk.o

# target to build an object file
libraries/Stk.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.o
.PHONY : libraries/Stk.cpp.o

libraries/Stk.i: libraries/Stk.cpp.i

.PHONY : libraries/Stk.i

# target to preprocess a source file
libraries/Stk.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.i
.PHONY : libraries/Stk.cpp.i

libraries/Stk.s: libraries/Stk.cpp.s

.PHONY : libraries/Stk.s

# target to generate assembly for a file
libraries/Stk.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/Stk.cpp.s
.PHONY : libraries/Stk.cpp.s

libraries/ring_buffer.o: libraries/ring_buffer.cpp.o

.PHONY : libraries/ring_buffer.o

# target to build an object file
libraries/ring_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.o
.PHONY : libraries/ring_buffer.cpp.o

libraries/ring_buffer.i: libraries/ring_buffer.cpp.i

.PHONY : libraries/ring_buffer.i

# target to preprocess a source file
libraries/ring_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.i
.PHONY : libraries/ring_buffer.cpp.i

libraries/ring_buffer.s: libraries/ring_buffer.cpp.s

.PHONY : libraries/ring_buffer.s

# target to generate assembly for a file
libraries/ring_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/libraries/ring_buffer.cpp.s
.PHONY : libraries/ring_buffer.cpp.s

sources/Frontieres.o: sources/Frontieres.cpp.o

.PHONY : sources/Frontieres.o

# target to build an object file
sources/Frontieres.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/Frontieres.cpp.o
.PHONY : sources/Frontieres.cpp.o

sources/Frontieres.i: sources/Frontieres.cpp.i

.PHONY : sources/Frontieres.i

# target to preprocess a source file
sources/Frontieres.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/Frontieres.cpp.i
.PHONY : sources/Frontieres.cpp.i

sources/Frontieres.s: sources/Frontieres.cpp.s

.PHONY : sources/Frontieres.s

# target to generate assembly for a file
sources/Frontieres.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/Frontieres.cpp.s
.PHONY : sources/Frontieres.cpp.s

sources/MyRtAudio.o: sources/MyRtAudio.cpp.o

.PHONY : sources/MyRtAudio.o

# target to build an object file
sources/MyRtAudio.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/MyRtAudio.cpp.o
.PHONY : sources/MyRtAudio.cpp.o

sources/MyRtAudio.i: sources/MyRtAudio.cpp.i

.PHONY : sources/MyRtAudio.i

# target to preprocess a source file
sources/MyRtAudio.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/MyRtAudio.cpp.i
.PHONY : sources/MyRtAudio.cpp.i

sources/MyRtAudio.s: sources/MyRtAudio.cpp.s

.PHONY : sources/MyRtAudio.s

# target to generate assembly for a file
sources/MyRtAudio.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/MyRtAudio.cpp.s
.PHONY : sources/MyRtAudio.cpp.s

sources/dsp/Window.o: sources/dsp/Window.cpp.o

.PHONY : sources/dsp/Window.o

# target to build an object file
sources/dsp/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/dsp/Window.cpp.o
.PHONY : sources/dsp/Window.cpp.o

sources/dsp/Window.i: sources/dsp/Window.cpp.i

.PHONY : sources/dsp/Window.i

# target to preprocess a source file
sources/dsp/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/dsp/Window.cpp.i
.PHONY : sources/dsp/Window.cpp.i

sources/dsp/Window.s: sources/dsp/Window.cpp.s

.PHONY : sources/dsp/Window.s

# target to generate assembly for a file
sources/dsp/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/dsp/Window.cpp.s
.PHONY : sources/dsp/Window.cpp.s

sources/interface/AdsrDialog.o: sources/interface/AdsrDialog.cpp.o

.PHONY : sources/interface/AdsrDialog.o

# target to build an object file
sources/interface/AdsrDialog.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/AdsrDialog.cpp.o
.PHONY : sources/interface/AdsrDialog.cpp.o

sources/interface/AdsrDialog.i: sources/interface/AdsrDialog.cpp.i

.PHONY : sources/interface/AdsrDialog.i

# target to preprocess a source file
sources/interface/AdsrDialog.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/AdsrDialog.cpp.i
.PHONY : sources/interface/AdsrDialog.cpp.i

sources/interface/AdsrDialog.s: sources/interface/AdsrDialog.cpp.s

.PHONY : sources/interface/AdsrDialog.s

# target to generate assembly for a file
sources/interface/AdsrDialog.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/AdsrDialog.cpp.s
.PHONY : sources/interface/AdsrDialog.cpp.s

sources/interface/MyGLApplication.o: sources/interface/MyGLApplication.cpp.o

.PHONY : sources/interface/MyGLApplication.o

# target to build an object file
sources/interface/MyGLApplication.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLApplication.cpp.o
.PHONY : sources/interface/MyGLApplication.cpp.o

sources/interface/MyGLApplication.i: sources/interface/MyGLApplication.cpp.i

.PHONY : sources/interface/MyGLApplication.i

# target to preprocess a source file
sources/interface/MyGLApplication.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLApplication.cpp.i
.PHONY : sources/interface/MyGLApplication.cpp.i

sources/interface/MyGLApplication.s: sources/interface/MyGLApplication.cpp.s

.PHONY : sources/interface/MyGLApplication.s

# target to generate assembly for a file
sources/interface/MyGLApplication.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLApplication.cpp.s
.PHONY : sources/interface/MyGLApplication.cpp.s

sources/interface/MyGLWindow.o: sources/interface/MyGLWindow.cpp.o

.PHONY : sources/interface/MyGLWindow.o

# target to build an object file
sources/interface/MyGLWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLWindow.cpp.o
.PHONY : sources/interface/MyGLWindow.cpp.o

sources/interface/MyGLWindow.i: sources/interface/MyGLWindow.cpp.i

.PHONY : sources/interface/MyGLWindow.i

# target to preprocess a source file
sources/interface/MyGLWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLWindow.cpp.i
.PHONY : sources/interface/MyGLWindow.cpp.i

sources/interface/MyGLWindow.s: sources/interface/MyGLWindow.cpp.s

.PHONY : sources/interface/MyGLWindow.s

# target to generate assembly for a file
sources/interface/MyGLWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/MyGLWindow.cpp.s
.PHONY : sources/interface/MyGLWindow.cpp.s

sources/interface/StartDialog.o: sources/interface/StartDialog.cpp.o

.PHONY : sources/interface/StartDialog.o

# target to build an object file
sources/interface/StartDialog.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/StartDialog.cpp.o
.PHONY : sources/interface/StartDialog.cpp.o

sources/interface/StartDialog.i: sources/interface/StartDialog.cpp.i

.PHONY : sources/interface/StartDialog.i

# target to preprocess a source file
sources/interface/StartDialog.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/StartDialog.cpp.i
.PHONY : sources/interface/StartDialog.cpp.i

sources/interface/StartDialog.s: sources/interface/StartDialog.cpp.s

.PHONY : sources/interface/StartDialog.s

# target to generate assembly for a file
sources/interface/StartDialog.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/interface/StartDialog.cpp.s
.PHONY : sources/interface/StartDialog.cpp.s

sources/model/Adsr.o: sources/model/Adsr.cpp.o

.PHONY : sources/model/Adsr.o

# target to build an object file
sources/model/Adsr.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Adsr.cpp.o
.PHONY : sources/model/Adsr.cpp.o

sources/model/Adsr.i: sources/model/Adsr.cpp.i

.PHONY : sources/model/Adsr.i

# target to preprocess a source file
sources/model/Adsr.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Adsr.cpp.i
.PHONY : sources/model/Adsr.cpp.i

sources/model/Adsr.s: sources/model/Adsr.cpp.s

.PHONY : sources/model/Adsr.s

# target to generate assembly for a file
sources/model/Adsr.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Adsr.cpp.s
.PHONY : sources/model/Adsr.cpp.s

sources/model/Cloud.o: sources/model/Cloud.cpp.o

.PHONY : sources/model/Cloud.o

# target to build an object file
sources/model/Cloud.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Cloud.cpp.o
.PHONY : sources/model/Cloud.cpp.o

sources/model/Cloud.i: sources/model/Cloud.cpp.i

.PHONY : sources/model/Cloud.i

# target to preprocess a source file
sources/model/Cloud.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Cloud.cpp.i
.PHONY : sources/model/Cloud.cpp.i

sources/model/Cloud.s: sources/model/Cloud.cpp.s

.PHONY : sources/model/Cloud.s

# target to generate assembly for a file
sources/model/Cloud.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Cloud.cpp.s
.PHONY : sources/model/Cloud.cpp.s

sources/model/Grain.o: sources/model/Grain.cpp.o

.PHONY : sources/model/Grain.o

# target to build an object file
sources/model/Grain.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Grain.cpp.o
.PHONY : sources/model/Grain.cpp.o

sources/model/Grain.i: sources/model/Grain.cpp.i

.PHONY : sources/model/Grain.i

# target to preprocess a source file
sources/model/Grain.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Grain.cpp.i
.PHONY : sources/model/Grain.cpp.i

sources/model/Grain.s: sources/model/Grain.cpp.s

.PHONY : sources/model/Grain.s

# target to generate assembly for a file
sources/model/Grain.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Grain.cpp.s
.PHONY : sources/model/Grain.cpp.s

sources/model/ParamAdsr.o: sources/model/ParamAdsr.cpp.o

.PHONY : sources/model/ParamAdsr.o

# target to build an object file
sources/model/ParamAdsr.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/ParamAdsr.cpp.o
.PHONY : sources/model/ParamAdsr.cpp.o

sources/model/ParamAdsr.i: sources/model/ParamAdsr.cpp.i

.PHONY : sources/model/ParamAdsr.i

# target to preprocess a source file
sources/model/ParamAdsr.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/ParamAdsr.cpp.i
.PHONY : sources/model/ParamAdsr.cpp.i

sources/model/ParamAdsr.s: sources/model/ParamAdsr.cpp.s

.PHONY : sources/model/ParamAdsr.s

# target to generate assembly for a file
sources/model/ParamAdsr.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/ParamAdsr.cpp.s
.PHONY : sources/model/ParamAdsr.cpp.s

sources/model/Sample.o: sources/model/Sample.cpp.o

.PHONY : sources/model/Sample.o

# target to build an object file
sources/model/Sample.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Sample.cpp.o
.PHONY : sources/model/Sample.cpp.o

sources/model/Sample.i: sources/model/Sample.cpp.i

.PHONY : sources/model/Sample.i

# target to preprocess a source file
sources/model/Sample.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Sample.cpp.i
.PHONY : sources/model/Sample.cpp.i

sources/model/Sample.s: sources/model/Sample.cpp.s

.PHONY : sources/model/Sample.s

# target to generate assembly for a file
sources/model/Sample.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Sample.cpp.s
.PHONY : sources/model/Sample.cpp.s

sources/model/Scene.o: sources/model/Scene.cpp.o

.PHONY : sources/model/Scene.o

# target to build an object file
sources/model/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Scene.cpp.o
.PHONY : sources/model/Scene.cpp.o

sources/model/Scene.i: sources/model/Scene.cpp.i

.PHONY : sources/model/Scene.i

# target to preprocess a source file
sources/model/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Scene.cpp.i
.PHONY : sources/model/Scene.cpp.i

sources/model/Scene.s: sources/model/Scene.cpp.s

.PHONY : sources/model/Scene.s

# target to generate assembly for a file
sources/model/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/model/Scene.cpp.s
.PHONY : sources/model/Scene.cpp.s

sources/utility/GTime.o: sources/utility/GTime.cpp.o

.PHONY : sources/utility/GTime.o

# target to build an object file
sources/utility/GTime.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/utility/GTime.cpp.o
.PHONY : sources/utility/GTime.cpp.o

sources/utility/GTime.i: sources/utility/GTime.cpp.i

.PHONY : sources/utility/GTime.i

# target to preprocess a source file
sources/utility/GTime.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/utility/GTime.cpp.i
.PHONY : sources/utility/GTime.cpp.i

sources/utility/GTime.s: sources/utility/GTime.cpp.s

.PHONY : sources/utility/GTime.s

# target to generate assembly for a file
sources/utility/GTime.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/utility/GTime.cpp.s
.PHONY : sources/utility/GTime.cpp.s

sources/visual/CloudVis.o: sources/visual/CloudVis.cpp.o

.PHONY : sources/visual/CloudVis.o

# target to build an object file
sources/visual/CloudVis.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/CloudVis.cpp.o
.PHONY : sources/visual/CloudVis.cpp.o

sources/visual/CloudVis.i: sources/visual/CloudVis.cpp.i

.PHONY : sources/visual/CloudVis.i

# target to preprocess a source file
sources/visual/CloudVis.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/CloudVis.cpp.i
.PHONY : sources/visual/CloudVis.cpp.i

sources/visual/CloudVis.s: sources/visual/CloudVis.cpp.s

.PHONY : sources/visual/CloudVis.s

# target to generate assembly for a file
sources/visual/CloudVis.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/CloudVis.cpp.s
.PHONY : sources/visual/CloudVis.cpp.s

sources/visual/GrainVis.o: sources/visual/GrainVis.cpp.o

.PHONY : sources/visual/GrainVis.o

# target to build an object file
sources/visual/GrainVis.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/GrainVis.cpp.o
.PHONY : sources/visual/GrainVis.cpp.o

sources/visual/GrainVis.i: sources/visual/GrainVis.cpp.i

.PHONY : sources/visual/GrainVis.i

# target to preprocess a source file
sources/visual/GrainVis.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/GrainVis.cpp.i
.PHONY : sources/visual/GrainVis.cpp.i

sources/visual/GrainVis.s: sources/visual/GrainVis.cpp.s

.PHONY : sources/visual/GrainVis.s

# target to generate assembly for a file
sources/visual/GrainVis.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/GrainVis.cpp.s
.PHONY : sources/visual/GrainVis.cpp.s

sources/visual/SampleVis.o: sources/visual/SampleVis.cpp.o

.PHONY : sources/visual/SampleVis.o

# target to build an object file
sources/visual/SampleVis.cpp.o:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/SampleVis.cpp.o
.PHONY : sources/visual/SampleVis.cpp.o

sources/visual/SampleVis.i: sources/visual/SampleVis.cpp.i

.PHONY : sources/visual/SampleVis.i

# target to preprocess a source file
sources/visual/SampleVis.cpp.i:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/SampleVis.cpp.i
.PHONY : sources/visual/SampleVis.cpp.i

sources/visual/SampleVis.s: sources/visual/SampleVis.cpp.s

.PHONY : sources/visual/SampleVis.s

# target to generate assembly for a file
sources/visual/SampleVis.cpp.s:
	$(MAKE) -f CMakeFiles/Frontieres.dir/build.make CMakeFiles/Frontieres.dir/sources/visual/SampleVis.cpp.s
.PHONY : sources/visual/SampleVis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Frontieres_translations"
	@echo "... edit_cache"
	@echo "... Frontieres"
	@echo "... rebuild_cache"
	@echo "... libraries/QtFont3D/QtFont3D.o"
	@echo "... libraries/QtFont3D/QtFont3D.i"
	@echo "... libraries/QtFont3D/QtFont3D.s"
	@echo "... libraries/RtAudio.o"
	@echo "... libraries/RtAudio.i"
	@echo "... libraries/RtAudio.s"
	@echo "... libraries/RtMidi.o"
	@echo "... libraries/RtMidi.i"
	@echo "... libraries/RtMidi.s"
	@echo "... libraries/Stk.o"
	@echo "... libraries/Stk.i"
	@echo "... libraries/Stk.s"
	@echo "... libraries/ring_buffer.o"
	@echo "... libraries/ring_buffer.i"
	@echo "... libraries/ring_buffer.s"
	@echo "... sources/Frontieres.o"
	@echo "... sources/Frontieres.i"
	@echo "... sources/Frontieres.s"
	@echo "... sources/MyRtAudio.o"
	@echo "... sources/MyRtAudio.i"
	@echo "... sources/MyRtAudio.s"
	@echo "... sources/dsp/Window.o"
	@echo "... sources/dsp/Window.i"
	@echo "... sources/dsp/Window.s"
	@echo "... sources/interface/AdsrDialog.o"
	@echo "... sources/interface/AdsrDialog.i"
	@echo "... sources/interface/AdsrDialog.s"
	@echo "... sources/interface/MyGLApplication.o"
	@echo "... sources/interface/MyGLApplication.i"
	@echo "... sources/interface/MyGLApplication.s"
	@echo "... sources/interface/MyGLWindow.o"
	@echo "... sources/interface/MyGLWindow.i"
	@echo "... sources/interface/MyGLWindow.s"
	@echo "... sources/interface/StartDialog.o"
	@echo "... sources/interface/StartDialog.i"
	@echo "... sources/interface/StartDialog.s"
	@echo "... sources/model/Adsr.o"
	@echo "... sources/model/Adsr.i"
	@echo "... sources/model/Adsr.s"
	@echo "... sources/model/Cloud.o"
	@echo "... sources/model/Cloud.i"
	@echo "... sources/model/Cloud.s"
	@echo "... sources/model/Grain.o"
	@echo "... sources/model/Grain.i"
	@echo "... sources/model/Grain.s"
	@echo "... sources/model/ParamAdsr.o"
	@echo "... sources/model/ParamAdsr.i"
	@echo "... sources/model/ParamAdsr.s"
	@echo "... sources/model/Sample.o"
	@echo "... sources/model/Sample.i"
	@echo "... sources/model/Sample.s"
	@echo "... sources/model/Scene.o"
	@echo "... sources/model/Scene.i"
	@echo "... sources/model/Scene.s"
	@echo "... sources/utility/GTime.o"
	@echo "... sources/utility/GTime.i"
	@echo "... sources/utility/GTime.s"
	@echo "... sources/visual/CloudVis.o"
	@echo "... sources/visual/CloudVis.i"
	@echo "... sources/visual/CloudVis.s"
	@echo "... sources/visual/GrainVis.o"
	@echo "... sources/visual/GrainVis.i"
	@echo "... sources/visual/GrainVis.s"
	@echo "... sources/visual/SampleVis.o"
	@echo "... sources/visual/SampleVis.i"
	@echo "... sources/visual/SampleVis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

