.TH FRONTIÈRES "1" "25 March 2019" "Frontières 0.0.0" "Manpage for Frontières"

.SH NAME
\fBFrontières\fP \- interactive granular sampler

.SH SYNOPSIS
.B Frontières
.br
.SH DESCRIPTION
.B Frontières
is an audio samples player which is visually managed thanks to "playback points" that you can configure.
.br
More information can be found at https://ccrma.stanford.edu/~carlsonc/256a/Borderlands/ .

.SH OPTIONS
.TP
\fB\-a\fR
autoconnection to jack system's output
.TP
\fB\-c\fR
allows to choose the channels' number (by default: 16)
.PP

.SH EXAMPLES
Simply launch the Frontieres binary (beware of the capital letter).

.SH AUTHOR
2011-2015 Christopher Carlson <carlsonc@ccrma.stanford.edu>
2018-2019 Jean Pierre Cimalando <jp-dev@inbox.ru>, Olivier Flatres <olivier.flatres@sfr.fr>, and Olivier Humbert <trebmuh@tuxfamily.org>
.br
This manpage has been written by Olivier Humbert (<trebmuh@tuxfamily.org>) on December the 9th, 2016 for the LibraZiK, and can be used by everyone.
