.TH FRONTIÈRES "1" "25 March 2019" "Frontières 0.0.0" "Page de manuel pour Frontières"

.SH NOM
\fBFrontières\fP \- échantillonneur granulaire interactif

.SH SYNOPSIS
.B Frontières
.br
.SH DESCRIPTION
.B Frontières
est un lecteur d'échantillons audio qui se gère visuellement avec des "points de lecture" que vous configurez.
.br
Davantage d'informations peuvent être trouvées à https://ccrma.stanford.edu/~carlsonc/256a/Borderlands/ .

.SH OPTIONS
.TP
\fB\-a\fR
autoconnexion aux sorties système jack
.TP
\fB\-c\fR
permet de choisir le nombre de canaux (par défaut : 16)
.PP
.SH EXEMPLES
Lancez simplement le binaire Frontieres (attention à la majuscule).

.SH AUTEUR
2011-2015 Christopher Carlson <carlsonc@ccrma.stanford.edu>
2018-2019 Jean Pierre Cimalando <jp-dev@inbox.ru>, Olivier Flatres <olivier.flatres@sfr.fr>, et Olivier Humbert <trebmuh@tuxfamily.org>
.br
Cette page de manuel a été écrite par Olivier Humbert (<trebmuh@tuxfamily.org>) le 9 décembre 2016 pour le projet LibraZiK et peut être utilisée par tout le monde.
