.TH BORDERLANDS "1" "9 December 2016" "Borderlands 0.4" "Manpage for Borderlands"

.SH NAME
\fBBorderlands\fP \- interactive granular sampler

.SH SYNOPSIS
.B Borderlands
.br
.SH DESCRIPTION
.B Borderlands
is an audio samples player which is visually managed thanks to "playback points" that you can configure.
.br
More information can be found at https://ccrma.stanford.edu/~carlsonc/256a/Borderlands/ .

.SH OPTIONS
.TP
There is no command line option.

.SH EXAMPLES
Simply launch the Borderlands binary (beware of the capital letter).

.SH AUTHOR
Christopher Carlson (carlsonc@ccrma.stanford.edu)
.br
This manpage has been written by Olivier Humbert (<trebmuh@tuxfamily.org>) on December the 9th, 2016 for the LibraZiK, and can be used by everyone.
