.TH BORDERLANDS "1" "9 décembre 2016" "Borderlands 0.4" "Page de manuel pour Borderlands"

.SH NOM
\fBBorderlands\fP \- échantillonneur granulaire interactif

.SH SYNOPSIS
.B Borderlands
.br
.SH DESCRIPTION
.B Borderlands
est un lecteur d'échantillons audio qui se gère visuellement avec des "points de lecture" que vous configurez.
.br
Davantage d'informations peuvent être trouvées à https://ccrma.stanford.edu/~carlsonc/256a/Borderlands/ .

.SH OPTIONS
.TP
Il n'y a pas d'option en ligne de commande.

.SH EXEMPLES
Lancez simplement le binaire Borderlands (attention à la majuscule).

.SH AUTEUR
Christopher Carlson (carlsonc@ccrma.stanford.edu)
.br
Cette page de manuel a été écrite par Olivier Humbert (<trebmuh@tuxfamily.org>) le 9 décembre 2016 pour le projet LibraZiK et peut être utilisée par tout le monde.
